name: navigator_reactive_guards
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2

dev_dependencies:
  beamer: ^1.0.0-pre.15.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
